package gitutil

import (
	"fmt"
	"time"

	"github.com/go-git/go-git/v6"
	"github.com/go-git/go-git/v6/plumbing/object"
)

func (g GitTags) Newer() TagInfo {
	return g.Tags[0]
}

func (g GitTags) Older() TagInfo {
	return g.Tags[len(g.Tags)-1]
}

func (g GitTags) IncrementPatch() string {
	n := g.Newer()
	return fmt.Sprintf("v%d.%d.%d", n.MajorVersion, n.MinorVersion, n.PatchVersion+1)
}

func (g GitTags) IncrementMinor() string {
	n := g.Newer()
	return fmt.Sprintf("v%d.%d.0", n.MajorVersion, n.MinorVersion+1)
}

func (g GitTags) IncrementMajor() string {
	n := g.Newer()
	return fmt.Sprintf("v%d.0.0", n.MajorVersion+1)
}

func (g GitTags) CreateTag(newTag string) {

	r, err := git.PlainOpen(g.Repo)
	if err != nil {
		panic(err)
	}

	_, err = r.CreateTag(newTag, g.Newer().Hash, &git.CreateTagOptions{
		Tagger: &object.Signature{
			Name:  "Tagger Bot",
			Email: "tagger@lab.local",
			When:  time.Now(),
		},
		Message: "Version generated by tagger",
		Signer:  nil,
	})

}

func (g GitTags) Dump() {

	t := g.Tags

	if len(t) == 0 {
		fmt.Println("Repository without tags.")
		return
	}

	fmt.Println("Tags:")
	for _, tag := range t {
		fmt.Printf("%s  %s\n", tag.Date.Format("2006-01-02 15:04"), tag.Name)
	}

}
