// Copyright (c) 2026 Daniel Montanari. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package cmd

import (
	"fmt"
	"os"
	"tagger/gitutil"

	"github.com/spf13/cobra"
)

var incMajor bool
var incMinor bool
var incPatch bool
var authorName string
var authorEmail string
var commitMessage string

var incCmd = &cobra.Command{

	Use:   "inc [repository path] [--dry-run|-d]",
	Short: "Create new tag incrementing version number.",
	Long: `inc [repository path] [flags] Create new tag incrementing version number. 
	Tags must follow the pattern vM.m.p.
	Incrementing a higher version level resets lower ones (e.g., a Major bump on v2.1.35 results in v3.0.0).
	`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {

		if len(gitTags.Tags) == 0 {
			// If there are no tags, we can't increment.
			// We could default to v0.1.0 or v0.0.1, but for now, we'll error.
			fmt.Println("No existing tags found to increment from.")
			os.Exit(1)
		}

		newTag := IncVersion(gitTags)

		if !dryRun {
			// Check for remote only when we are about to create and push a tag.
			if !gitTags.HaveRemote() {
				fmt.Println("Error: cannot push tag, no remote is configured for this repository.")
				os.Exit(1)
			}

			CreateTag(gitTags, newTag)
			err := gitTags.Push(newTag)
			if err != nil {
				fmt.Println(err)
			}
		}

	},
}

func IncVersion(tags gitutil.GitTags) string {

	if verbose {
		fmt.Printf("%s -> ", tags.Newer().Name)
	}

	var newTag string

	if incMajor {
		newTag = tags.IncrementMajor()
	} else if incMinor {
		newTag = tags.IncrementMinor()
	} else if incPatch {
		newTag = tags.IncrementPatch()
	}

	fmt.Println(newTag)

	return newTag

}

func CreateTag(tags gitutil.GitTags, newTag string) {

	if verbose {
		fmt.Printf("%s -> ", tags.Newer().Name)
	}

	fmt.Println(newTag)
	err := tags.CreateTag(newTag, authorName, authorEmail, commitMessage)
	if err != nil {
		fmt.Printf("Error creating tag: %v\n", err)
		os.Exit(1)
	}
}

func init() {

	incCmd.Flags().BoolVarP(&incMajor, "major", "M", false, "Increment major version")
	incCmd.Flags().BoolVarP(&incMinor, "minor", "m", false, "Increment minor version")
	incCmd.Flags().BoolVarP(&incPatch, "patch", "p", false, "Increment patch version")
	incCmd.Flags().StringVarP(&authorName, "author", "a", "Tagger", "Author for commit")
	incCmd.Flags().StringVarP(&authorEmail, "email", "e", "tagger@bot", "Email for commit")
	incCmd.Flags().StringVarP(&commitMessage, "message", "", "Version generated by tagger", "Commit message")

	rootCmd.AddCommand(incCmd)
}
